blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/your-repo/issues/new?template=bug_report.md
    about: Report a problem with the project.
  - name: Feature Request
    url: https://github.com/your-repo/issues/new?template=feature_request.md
    about: Suggest a new idea or enhancement.
  - name: Documentation Request
    url: https://github.com/your-repo/issues/new?template=documentation_request.md
    about: Suggest improvements to the documentation.
